### PR TITLE
Fix default attribute regression (#13)

### PR DESCRIPTION
**Pull request by tyranron**
This PR fixes the regression of parsing `#[default(<expr>)]` attribute introduced in #11 and described in #13.

### CODE REVIEW

**Comment by idanarye** [comment]
Sorry, but I'm already working on a solution...

**Comment by tyranron** [comment]
@idanarye it's okay... I don't pretend. I just need a fix, because it's blocking upgrade on my projects. Feel free to close if you don't need it.

**Comment by idanarye** [comment]
It's in the CI now, and then I'll publish 7.1.

**Comment by idanarye** [comment]
Thanks for the effort anyway!

**Pull request closed without merging**
